[package]
name = "tiny-tile-proxy"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "TinyTileProxy"
path = "src/main.rs"

[dependencies]
reqwest = "0.12.7"
tokio = { version = "1", features = ["full"] }