[package]
name = "webp_to_png"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = [
  "webp",
  "png",
] }
anyhow = { workspace = true }
